# Generated by Django 3.1 on 2021-04-23 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 23, 23, 54, 47, 895738)),
        ),
    ]
