# Generated by Django 3.1.8 on 2021-04-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210425_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='error.jpg', null=True),
        ),
    ]
